const views=[...document.querySelectorAll('.view')],mods=[...document.querySelectorAll('.modal')],q=document.getElementById('questionText'),p=document.getElementById('progressText'),f=document.getElementById('progressFill'),g=document.getElementById('guessName'),c=document.getElementById('confidenceValue'),cf=document.getElementById('confidenceFill');
const key='whoState';
const state=JSON.parse(localStorage.getItem(key)||'{}');
const data=state.data||{q:'Is your character real?',yes:{q:'Is your character a superhero?',yes:{a:'Batman'},no:{q:'Is your character a musician?',yes:{a:'Taylor Swift'},no:{a:'Elon Musk'}}},no:{q:'Is your character fictional?',yes:{q:'Is your character a detective?',yes:{a:'Sherlock Holmes'},no:{a:'Naruto'}},no:{a:'Cristiano Ronaldo'}}};
const history=state.history||[];
const game={view:'landing',path:[],node:data,history};
const save=()=>localStorage.setItem(key,JSON.stringify({data,history:game.history.slice(0,8)}));
const show=v=>{game.view=v;views.forEach(x=>x.classList.toggle('is-active',x.dataset.view===v));};
const open=id=>document.getElementById(id)?.showModal();
const closeAll=()=>mods.forEach(m=>m.open&&m.close());
const renderHistory=()=>{const box=document.querySelector('#historyModal .modal-card');box.querySelectorAll('.history-item').forEach(n=>n.remove());game.history.forEach(r=>{const d=document.createElement('div');d.className='history-item';d.innerHTML=`<span>${r.name}</span><small>${r.conf}% · ${r.ok?'correct':'learned'}</small>`;box.appendChild(d);});};
const setProgress=i=>{const total=game.path.length+1;const pct=Math.min(100,Math.round((i/total)*100));p.style.width='';p.textContent=i+' / '+total;f.style.width=pct+'%';};
const loadNode=()=>{const n=game.node;if(n.a){g.textContent=n.a;const conf=Math.max(68,100-game.path.length*8);c.textContent=conf+'%';cf.style.width=conf+'%';game.history.unshift({name:n.a,conf,ok:true,at:new Date().toLocaleDateString()});game.history.splice(8);save();renderHistory();show('result');return;}q.textContent=n.q;setProgress(game.path.length+1);show('game');};
const start=()=>{game.path=[];game.node=data;loadNode();};
const answer=a=>{game.path.push(a);game.node=game.node[a]||game.node;save();loadNode();};
const learn=(name,question,answerSide)=>{const old=JSON.parse(JSON.stringify(game.node));const guessed=old.a||'this guess';const leaf=answerSide==='yes'?{yes:{a:name},no:{a:guessed}}:{yes:{a:guessed},no:{a:name}};Object.assign(game.node,{q:question,...leaf});game.history.unshift({name,conf:100,ok:false,at:new Date().toLocaleDateString()});game.history.splice(8);save();renderHistory();show('result');};
document.addEventListener('click',e=>{const a=e.target.closest('[data-action]')?.dataset.action,o=e.target.closest('[data-open]')?.dataset.open,ans=e.target.closest('[data-answer]')?.dataset.answer;if(a==='startGame'||a==='restart')start();if(a==='saveLearn'){const form=document.getElementById('wrongModal');const name=form.querySelector('[name="correctName"]').value.trim();const question=form.querySelector('[name="distinguishingQuestion"]').value.trim();const side=form.querySelector('[name="correctSide"]').value; if(name&&question)learn(name,question,side);}if(o)open(o);if(ans)answer(ans);});
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeAll();if(game.view!=='game')return;const map={y:'yes',n:'no',p:'probably',h:'probably_not','?':'dont_know'};if(map[e.key.toLowerCase()])answer(map[e.key.toLowerCase()]);});
renderHistory();show('landing');